spring:
    datasource:
        url: 'jdbc:h2:mem:myapp'
        username: 'user'
        password: ''
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true